

# 1) Register John as user.
POST http://localhost:8080/uaa/signup/user
Content-Type: application/json

{"username":  "John", "password": "hello123"}


###

# 2) Register Mike as Service_provider.
POST http://localhost:8080/uaa/signup/service_provider
Content-Type: application/json

{"username":  "Mike", "password": "hello123"}


### 
# 3) Login with John's credentials 
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "John",
  "password": "hello123"
}


###
# 4) Login with Mike Credentials. 
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "Mike",
  "password": "hello123"
}



###
# 5) Submit a Service Request. 
POST http://localhost:8080/requests/api/submit
Content-Type: application/json
Authorization: Bearer <token> # replace <token> with the token that you received in Step 3

{
     "type":"Maintenance",
     "title":"Maintenance",
     "detail":"A Full Maintenance for my apartement",
      "city":"yourCity"
}


###
# 6) Submit Offer
POST http://localhost:8080/offers/api/submit
Content-Type: application/json
Authorization: Bearer <token> # replace <token> with the token that you received in Step 4

{
   "requestNumber": "John_0", 
    "message": "I'd like to take for $500 ",
    "price": 500
}


###
# 7) get the offers of a service request 
GET http://localhost:8080/offers/api/offers/John_0
Authorization: Bearer <token> # replace <token> with the token that you received in Step 3

###
# 8) Accept Offer
GET http://localhost:8080/requests/api/requests/accept/John_0/Mike_1
Authorization: Bearer <token> # replace <token> with the token that you received in Step 3

###
# 9) Reject Offer
GET http://localhost:8080/requests/api/requests/reject/John_0/Mike_3
Authorization: Bearer <token> # replace <token> with the token that you received in Step 3

###
